# Generated by Django 5.1.7 on 2025-03-20 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('machine_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OK', 'OK'), ('WARNING', 'Warning'), ('FAULT', 'Fault')], default='OK', max_length=10)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Machinery',
            },
        ),
        migrations.CreateModel(
            name='MachineryAssignment',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_received', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineries.machineries')),
            ],
        ),
        migrations.CreateModel(
            name='MachineryCollection',
            fields=[
                ('mach_coll_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineries.collection')),
                ('machineries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machineries.machineries')),
            ],
            options={
                'unique_together': {('collection', 'machineries')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='machines',
            field=models.ManyToManyField(through='machineries.MachineryCollection', to='machineries.machineries'),
        ),
    ]
